using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Strada.Core.DI.Attributes;
using UnityEditor;
using UnityEngine;

namespace Strada.Core.Editor.CodeGen
{
    public static class FactoryGenerator
    {
        private const string GeneratedFolder = "Assets/Strada.Generated";
        private const string GeneratedFile = "GeneratedFactories.cs";

        [MenuItem("Strada/Generate Factories")]
        public static void GenerateFactories()
        {
            var types = FindTypesWithStradaService();
            if (types.Count == 0)
            {
                Debug.Log("[Strada] No types with [StradaService] attribute found.");
                return;
            }

            var code = GenerateFactoryCode(types);

            if (!Directory.Exists(GeneratedFolder))
                Directory.CreateDirectory(GeneratedFolder);

            var path = Path.Combine(GeneratedFolder, GeneratedFile);
            File.WriteAllText(path, code);
            AssetDatabase.Refresh();

            Debug.Log($"[Strada] Generated factories for {types.Count} types at {path}");
        }

        private static List<Type> FindTypesWithStradaService()
        {
            var result = new List<Type>();

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (assembly.IsDynamic)
                    continue;

                try
                {
                    foreach (var type in assembly.GetTypes())
                    {
                        if (type.IsAbstract || type.IsInterface)
                            continue;

                        var attr = type.GetCustomAttribute<StradaServiceAttribute>();
                        if (attr != null)
                            result.Add(type);
                    }
                }
                catch
                {
                }
            }

            return result;
        }

        private static string GenerateFactoryCode(List<Type> types)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by Strada Factory Generator");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine("using Strada.Core.DI;");
            sb.AppendLine();
            sb.AppendLine("namespace Strada.Generated");
            sb.AppendLine("{");

            foreach (var type in types)
            {
                GenerateFactoryForType(sb, type);
            }

            sb.AppendLine();
            sb.AppendLine("    public static class GeneratedFactoryInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");

            foreach (var type in types)
            {
                var fullName = GetFullTypeName(type);
                var factoryName = GetFactoryName(type);
                sb.AppendLine($"            DirectFactory<{fullName}>.Delegate = {factoryName}.Create;");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void GenerateFactoryForType(StringBuilder sb, Type type)
        {
            var constructor = GetBestConstructor(type);
            var parameters = constructor?.GetParameters() ?? Array.Empty<ParameterInfo>();

            var fullName = GetFullTypeName(type);
            var factoryName = GetFactoryName(type);

            sb.AppendLine();
            sb.AppendLine($"    public static class {factoryName}");
            sb.AppendLine("    {");
            sb.Append($"        public static {fullName} Create(IContainer c) => new {fullName}(");

            for (int i = 0; i < parameters.Length; i++)
            {
                if (i > 0)
                    sb.Append(", ");

                var paramType = parameters[i].ParameterType;
                var paramTypeName = GetFullTypeName(paramType);
                sb.Append($"c.Resolve<{paramTypeName}>()");
            }

            sb.AppendLine(");");
            sb.AppendLine("    }");
        }

        private static ConstructorInfo GetBestConstructor(Type type)
        {
            var constructors = type.GetConstructors(BindingFlags.Public | BindingFlags.Instance);
            if (constructors.Length == 0)
                return null;

            return constructors.OrderByDescending(c => c.GetParameters().Length).First();
        }

        private static string GetFullTypeName(Type type)
        {
            if (!type.IsGenericType)
                return type.FullName?.Replace("+", ".") ?? type.Name;

            var genericDef = type.GetGenericTypeDefinition();
            var baseName = genericDef.FullName;
            if (baseName == null)
                return type.Name;

            var tickIndex = baseName.IndexOf('`');
            if (tickIndex > 0)
                baseName = baseName.Substring(0, tickIndex);

            var args = type.GetGenericArguments();
            var argNames = string.Join(", ", args.Select(GetFullTypeName));

            return $"{baseName.Replace("+", ".")}<{argNames}>";
        }

        private static string GetFactoryName(Type type)
        {
            var name = type.Name;
            var tickIndex = name.IndexOf('`');
            if (tickIndex > 0)
                name = name.Substring(0, tickIndex);

            return $"{name}_Factory";
        }
    }
}
