using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Strada.Core.Modules;
using UnityEditor;
using UnityEngine;

namespace Strada.Core.Editor.CodeGen
{
    /// <summary>
    /// Generates a registry of all ModuleConfig ScriptableObjects found in the project.
    /// The generated file provides easy access to module metadata and validation utilities.
    /// </summary>
    public static class ModuleInitializerGenerator
    {
        private const string GeneratedFile = "GeneratedModuleInitializer.cs";

        [MenuItem("Strada/Generate Module Registry")]
        public static void GenerateModuleRegistry()
        {
            var modules = FindAllModuleConfigs();
            if (modules.Count == 0)
            {
                Debug.Log("[Strada] No ModuleConfig assets found.");
                return;
            }

            var code = GenerateRegistryCode(modules);

            StradaCodeGenerator.EnsureGeneratedFolder();

            var path = Path.Combine(StradaCodeGenerator.GeneratedFolder, GeneratedFile);
            File.WriteAllText(path, code);
            AssetDatabase.Refresh();

            Debug.Log($"[Strada] Generated module registry with {modules.Count} modules at {path}");
        }

        private static List<ModuleConfigInfo> FindAllModuleConfigs()
        {
            var result = new List<ModuleConfigInfo>();
            var guids = AssetDatabase.FindAssets("t:ModuleConfig");

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var config = AssetDatabase.LoadAssetAtPath<ModuleConfig>(path);

                if (config != null)
                {
                    result.Add(new ModuleConfigInfo
                    {
                        GUID = guid,
                        AssetPath = path,
                        ModuleName = config.ModuleName,
                        TypeName = config.GetType().FullName,
                        Priority = config.Priority,
                        Enabled = config.Enabled
                    });
                }
            }

            return result.OrderBy(m => m.Priority).ThenBy(m => m.ModuleName).ToList();
        }

        private static string GenerateRegistryCode(List<ModuleConfigInfo> modules)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by Strada Module Registry Generator");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Strada.Core.Modules;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Strada.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Registry of all ModuleConfig assets found in the project.");
            sb.AppendLine("    /// Use this for validation, discovery, and debugging purposes.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class GeneratedModuleRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Information about a discovered module.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public readonly struct ModuleInfo");
            sb.AppendLine("        {");
            sb.AppendLine("            public readonly string GUID;");
            sb.AppendLine("            public readonly string AssetPath;");
            sb.AppendLine("            public readonly string ModuleName;");
            sb.AppendLine("            public readonly string TypeName;");
            sb.AppendLine("            public readonly int Priority;");
            sb.AppendLine();
            sb.AppendLine("            public ModuleInfo(string guid, string assetPath, string moduleName, string typeName, int priority)");
            sb.AppendLine("            {");
            sb.AppendLine("                GUID = guid;");
            sb.AppendLine("                AssetPath = assetPath;");
            sb.AppendLine("                ModuleName = moduleName;");
            sb.AppendLine("                TypeName = typeName;");
            sb.AppendLine("                Priority = priority;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// All discovered module configurations at generation time.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static readonly ModuleInfo[] DiscoveredModules = new ModuleInfo[]");
            sb.AppendLine("        {");

            foreach (var module in modules)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(m.Type);
                sb.AppendLine($"            typeof({typeName}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Loads all discovered ModuleConfig assets from the AssetDatabase.");
            sb.AppendLine("        /// Editor-only: Use for validation and tooling.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static List<ModuleConfig> LoadAllFromAssetDatabase()");
            sb.AppendLine("        {");

            foreach (var m in modules)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(m.Type);
                sb.AppendLine($"            registry.RegisterModule(new {typeName}(), {m.Priority});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Validates that all discovered modules still exist and are properly configured.");
            sb.AppendLine("        /// Returns a list of validation issues, if any.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static List<string> ValidateModules()");
            sb.AppendLine("        {");
            sb.AppendLine("            var issues = new List<string>();");
            sb.AppendLine("            foreach (var info in DiscoveredModules)");
            sb.AppendLine("            {");

            foreach (var m in modules)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(m.Type);
                sb.AppendLine($"                new {typeName}(),");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("#endif");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static bool IsTypeAccessible(Type type)
        {
            public string GUID;
            public string AssetPath;
            public string ModuleName;
            public string TypeName;
            public int Priority;
            public bool Enabled;
        }
    }
}
