using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Strada.Core.Module;
using UnityEditor;
using UnityEngine;

namespace Strada.Core.Editor.CodeGen
{
    public static class ModuleInitializerGenerator
    {
        private const string GeneratedFolder = "Assets/Strada.Generated";
        private const string GeneratedFile = "GeneratedModuleInitializer.cs";

        [MenuItem("Strada/Generate Module Initializer")]
        public static void GenerateModuleInitializer()
        {
            var modules = FindAllModules();
            if (modules.Count == 0)
            {
                Debug.Log("[Strada] No IModule implementations found.");
                return;
            }

            var code = GenerateInitializerCode(modules);

            if (!Directory.Exists(GeneratedFolder))
                Directory.CreateDirectory(GeneratedFolder);

            var path = Path.Combine(GeneratedFolder, GeneratedFile);
            File.WriteAllText(path, code);
            AssetDatabase.Refresh();

            Debug.Log($"[Strada] Generated module initializer with {modules.Count} modules at {path}");
        }

        private static List<ModuleInfo> FindAllModules()
        {
            var result = new List<ModuleInfo>();

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (assembly.IsDynamic || assembly.FullName.StartsWith("Unity.") || assembly.FullName.StartsWith("System"))
                    continue;

                try
                {
                    foreach (var type in assembly.GetTypes())
                    {
                        if (type.IsAbstract || type.IsInterface)
                            continue;

                        if (!typeof(IModule).IsAssignableFrom(type))
                            continue;

                        var attr = type.GetCustomAttribute<ModulePriorityAttribute>();
                        int priority = attr?.Priority ?? 0;
                        string[] dependencies = attr?.Dependencies ?? Array.Empty<string>();
                        result.Add(new ModuleInfo(type, priority, dependencies));
                    }
                }
                catch { }
            }

            return result.OrderBy(x => x.Priority).ToList();
        }

        private static string GenerateInitializerCode(List<ModuleInfo> modules)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by Strada Module Initializer Generator");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Strada.Core.Module;");
            sb.AppendLine("using Strada.Core.Modules;");
            sb.AppendLine("using Strada.Core.DI;");
            sb.AppendLine();
            sb.AppendLine("namespace Strada.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedModuleInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly Type[] ModuleTypes = new Type[]");
            sb.AppendLine("        {");

            foreach (var m in modules)
            {
                var typeName = GetFullTypeName(m.Type);
                sb.AppendLine($"            typeof({typeName}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(ModuleRegistry registry, IContainer container)");
            sb.AppendLine("        {");

            foreach (var m in modules)
            {
                var typeName = GetFullTypeName(m.Type);
                var depsArray = m.Dependencies.Length > 0
                    ? $"new[] {{ {string.Join(", ", m.Dependencies.Select(d => $"\"{d}\""))} }}"
                    : "Array.Empty<string>()";

                sb.AppendLine($"            registry.Register(new {typeName}(), {m.Priority}, {depsArray});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static List<IModule> CreateAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            return new List<IModule>");
            sb.AppendLine("            {");

            foreach (var m in modules)
            {
                var typeName = GetFullTypeName(m.Type);
                sb.AppendLine($"                new {typeName}(),");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GetFullTypeName(Type type)
        {
            if (!type.IsGenericType)
                return type.FullName?.Replace("+", ".") ?? type.Name;

            var genericDef = type.GetGenericTypeDefinition();
            var baseName = genericDef.FullName;
            if (baseName == null)
                return type.Name;

            var tickIndex = baseName.IndexOf('`');
            if (tickIndex > 0)
                baseName = baseName.Substring(0, tickIndex);

            var args = type.GetGenericArguments();
            var argNames = string.Join(", ", args.Select(GetFullTypeName));

            return $"{baseName.Replace("+", ".")}<{argNames}>";
        }

        private struct ModuleInfo
        {
            public Type Type;
            public int Priority;
            public string[] Dependencies;

            public ModuleInfo(Type type, int priority, string[] dependencies)
            {
                Type = type;
                Priority = priority;
                Dependencies = dependencies;
            }
        }
    }

    [AttributeUsage(AttributeTargets.Class)]
    public class ModulePriorityAttribute : Attribute
    {
        public int Priority { get; }
        public string[] Dependencies { get; }

        public ModulePriorityAttribute(int priority = 0, params string[] dependencies)
        {
            Priority = priority;
            Dependencies = dependencies;
        }
    }
}
