using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Strada.Core.Modules;
using UnityEditor;
using UnityEngine;

namespace Strada.Core.Editor.CodeGen
{
    /// <summary>
    /// Generates a registry of all ModuleConfig ScriptableObjects found in the project.
    /// The generated file provides easy access to module metadata and validation utilities.
    /// </summary>
    public static class ModuleInitializerGenerator
    {
        private const string GeneratedFile = "GeneratedModuleInitializer.cs";

        [MenuItem("Strada/Generate Module Registry")]
        public static void GenerateModuleRegistry()
        {
            var modules = FindAllModuleConfigs();
            if (modules.Count == 0)
            {
                Debug.Log("[Strada] No ModuleConfig assets found.");
                return;
            }

            var code = GenerateRegistryCode(modules);

            StradaCodeGenerator.EnsureGeneratedFolder();

            var path = Path.Combine(StradaCodeGenerator.GeneratedFolder, GeneratedFile);
            File.WriteAllText(path, code);
            AssetDatabase.Refresh();

            Debug.Log($"[Strada] Generated module registry with {modules.Count} modules at {path}");
        }

        private static List<ModuleConfigInfo> FindAllModuleConfigs()
        {
            var result = new List<ModuleConfigInfo>();
            var guids = AssetDatabase.FindAssets("t:ModuleConfig");

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var config = AssetDatabase.LoadAssetAtPath<ModuleConfig>(path);
                if (config == null)
                {
                    continue;
                }

                result.Add(new ModuleConfigInfo(
                    guid,
                    path,
                    config.ModuleName,
                    config.GetType().FullName ?? config.GetType().Name,
                    config.Priority,
                    config.Enabled));
            }

            return result
                .OrderBy(module => module.Priority)
                .ThenBy(module => module.ModuleName)
                .ToList();
        }

        private static string GenerateRegistryCode(List<ModuleConfigInfo> modules)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by Strada Module Registry Generator");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Strada.Core.Modules;");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("#endif");
            sb.AppendLine();
            sb.AppendLine("namespace Strada.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedModuleRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public readonly struct ModuleInfo");
            sb.AppendLine("        {");
            sb.AppendLine("            public readonly string GUID;");
            sb.AppendLine("            public readonly string AssetPath;");
            sb.AppendLine("            public readonly string ModuleName;");
            sb.AppendLine("            public readonly string TypeName;");
            sb.AppendLine("            public readonly int Priority;");
            sb.AppendLine("            public readonly bool Enabled;");
            sb.AppendLine();
            sb.AppendLine("            public ModuleInfo(string guid, string assetPath, string moduleName, string typeName, int priority, bool enabled)");
            sb.AppendLine("            {");
            sb.AppendLine("                GUID = guid;");
            sb.AppendLine("                AssetPath = assetPath;");
            sb.AppendLine("                ModuleName = moduleName;");
            sb.AppendLine("                TypeName = typeName;");
            sb.AppendLine("                Priority = priority;");
            sb.AppendLine("                Enabled = enabled;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static readonly ModuleInfo[] DiscoveredModules = new ModuleInfo[]");
            sb.AppendLine("        {");

            foreach (var module in modules)
            {
                sb.AppendLine(
                    $"            new ModuleInfo({ToLiteral(module.GUID)}, {ToLiteral(module.AssetPath)}, {ToLiteral(module.ModuleName)}, {ToLiteral(module.TypeName)}, {module.Priority}, {(module.Enabled ? "true" : "false")}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("        public static List<ModuleConfig> LoadAllFromAssetDatabase()");
            sb.AppendLine("        {");
            sb.AppendLine("            var modules = new List<ModuleConfig>(DiscoveredModules.Length);");
            sb.AppendLine("            foreach (var info in DiscoveredModules)");
            sb.AppendLine("            {");
            sb.AppendLine("                var module = AssetDatabase.LoadAssetAtPath<ModuleConfig>(info.AssetPath);");
            sb.AppendLine("                if (module != null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    modules.Add(module);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            return modules;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static List<string> ValidateModules()");
            sb.AppendLine("        {");
            sb.AppendLine("            var issues = new List<string>();");
            sb.AppendLine("            foreach (var info in DiscoveredModules)");
            sb.AppendLine("            {");
            sb.AppendLine("                var module = AssetDatabase.LoadAssetAtPath<ModuleConfig>(info.AssetPath);");
            sb.AppendLine("                if (module == null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    issues.Add($\"Missing module asset: {info.ModuleName} ({info.AssetPath})\");");
            sb.AppendLine("                    continue;");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                var currentTypeName = module.GetType().FullName ?? module.GetType().Name;");
            sb.AppendLine("                if (currentTypeName != info.TypeName)");
            sb.AppendLine("                {");
            sb.AppendLine("                    issues.Add($\"Module type mismatch for {info.ModuleName}: expected {info.TypeName}, found {currentTypeName}\");");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            return issues;");
            sb.AppendLine("        }");
            sb.AppendLine("#endif");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string ToLiteral(string value)
        {
            if (value == null)
            {
                return "null";
            }

            return "\"" + value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t") + "\"";
        }

        private readonly struct ModuleConfigInfo
        {
            public readonly string GUID;
            public readonly string AssetPath;
            public readonly string ModuleName;
            public readonly string TypeName;
            public readonly int Priority;
            public readonly bool Enabled;

            public ModuleConfigInfo(string guid, string assetPath, string moduleName, string typeName, int priority, bool enabled)
            {
                GUID = guid;
                AssetPath = assetPath;
                ModuleName = moduleName;
                TypeName = typeName;
                Priority = priority;
                Enabled = enabled;
            }
        }
    }
}
