using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Strada.Core.ECS;
using UnityEditor;
using UnityEngine;

namespace Strada.Core.Editor.CodeGen
{
    public static class SystemRegistryGenerator
    {
        private const string GeneratedFile = "GeneratedSystemRegistry.cs";

        [MenuItem("Strada/Generate System Registry")]
        public static void GenerateSystemRegistry()
        {
            var systems = FindAllSystems();
            if (systems.Count == 0)
            {
                Debug.Log("[Strada] No ISystem implementations found.");
                return;
            }

            var code = GenerateRegistryCode(systems);

            StradaCodeGenerator.EnsureGeneratedFolder();

            var path = Path.Combine(StradaCodeGenerator.GeneratedFolder, GeneratedFile);
            File.WriteAllText(path, code);
            AssetDatabase.Refresh();

            Debug.Log($"[Strada] Generated system registry with {systems.Count} systems at {path}");
        }

        private static List<SystemInfo> FindAllSystems()
        {
            var result = new List<SystemInfo>();

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (assembly.IsDynamic || assembly.FullName.StartsWith("Unity") || assembly.FullName.StartsWith("System"))
                    continue;

                try
                {
                    foreach (var type in assembly.GetTypes())
                    {
                        if (type.IsAbstract || type.IsInterface)
                            continue;

                        if (!typeof(ISystem).IsAssignableFrom(type))
                            continue;

                        var attr = type.GetCustomAttribute<SystemOrderAttribute>();
                        int order = attr?.Order ?? 0;
                        result.Add(new SystemInfo(type, order));
                    }
                }
                catch { }
            }

            return result.OrderBy(x => x.Order).ToList();
        }

        private static string GenerateRegistryCode(List<SystemInfo> systems)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by Strada System Registry Generator");
            sb.AppendLine("// Do not modify this file manually");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Strada.Core.ECS;");
            sb.AppendLine("using Strada.Core.DI;");
            sb.AppendLine();
            sb.AppendLine("namespace Strada.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedSystemRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly Type[] SystemTypes = new Type[]");
            sb.AppendLine("        {");

            foreach (var s in systems)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(s.Type);
                sb.AppendLine($"            typeof({typeName}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(IContainerBuilder builder)");
            sb.AppendLine("        {");

            foreach (var s in systems)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(s.Type);
                sb.AppendLine($"            builder.Register<{typeName}>(Lifetime.Singleton);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static List<ISystem> CreateAll(IContainer container)");
            sb.AppendLine("        {");
            sb.AppendLine("            var systems = new List<ISystem>(SystemTypes.Length);");

            foreach (var s in systems)
            {
                var typeName = StradaCodeGenerator.GetFullTypeName(s.Type);
                sb.AppendLine($"            systems.Add(container.Resolve<{typeName}>());");
            }

            sb.AppendLine("            return systems;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private struct SystemInfo
        {
            public Type Type;
            public int Order;

            public SystemInfo(Type type, int order)
            {
                Type = type;
                Order = order;
            }
        }
    }

    [AttributeUsage(AttributeTargets.Class)]
    public class SystemOrderAttribute : Attribute
    {
        public int Order { get; }

        public SystemOrderAttribute(int order = 0)
        {
            Order = order;
        }
    }
}
