// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by Strada Module Generator v1.0
// =============================================================================

using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Strada.Core.Editor.Templates
{
    /// <summary>
    /// Provides code templates for Strada framework components.
    /// Generates properly structured code with correct namespaces and using statements.
    /// </summary>
    public static class StradaTemplates
    {
        private const string GeneratedHeader = @"// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by Strada Module Generator v1.0
// =============================================================================

";

        /// <summary>
        /// Generates an ISystem implementation template.
        /// </summary>
        /// <param name="className">The name of the system class.</param>
        /// <param name="namespaceName">The namespace for the class.</param>
        /// <param name="systemOrder">The system execution order (default 0).</param>
        /// <returns>The generated code.</returns>
        public static string GenerateSystem(string className, string namespaceName, int systemOrder = 0)
        {
            if (!className.EndsWith("System"))
                className += "System";

            var usings = UsingStatementGenerator.GenerateUsingBlock(
                TemplateContextDetector.TemplateType.System);

            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine(usings);
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// ECS System that processes entities each frame.");
            sb.AppendLine("    /// Inherits from SystemBase for automatic EntityManager and MessageBus injection.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    [SystemOrder({systemOrder})]");
            sb.AppendLine($"    public class {className} : SystemBase");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Called once when the system is first created.");
            sb.AppendLine("        /// EntityManager and MessageBus are available via inherited properties.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        protected override void OnInitialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Initialize system resources here");
            sb.AppendLine("            // EntityManager is available for entity operations");
            sb.AppendLine("            // MessageBus is available for messaging");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Called every frame to process entities.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"deltaTime\">The time elapsed since the last frame.</param>");
            sb.AppendLine("        protected override void OnUpdate(float deltaTime)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Process entities here");
            sb.AppendLine("            // Example: ForEach<MyComponent>((entity, ref c) => { ... });");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Called when the system is disposed.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        protected override void OnDispose()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Cleanup system resources here");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates a Controller template.
        /// </summary>
        public static string GenerateController(string className, string namespaceName)
        {
            if (!className.EndsWith("Controller"))
                className += "Controller";

            var usings = UsingStatementGenerator.GenerateUsingBlock(
                TemplateContextDetector.TemplateType.Controller);

            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine(usings);
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Controller that handles input and coordinates between Views and Services.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public class {className} : Controller");
            sb.AppendLine("    {");
            sb.AppendLine("        public override void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.Initialize();");
            sb.AppendLine("            // Initialize controller");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void Tick(float deltaTime)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Handle per-frame logic");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void Shutdown()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Cleanup controller");
            sb.AppendLine("            base.Shutdown();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates a Service template.
        /// </summary>
        public static string GenerateService(string className, string namespaceName)
        {
            if (!className.EndsWith("Service"))
                className += "Service";

            var usings = UsingStatementGenerator.GenerateUsingBlock(
                TemplateContextDetector.TemplateType.Service);

            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine(usings);
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Service containing business logic, shared across modules.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public class {className} : StradaService");
            sb.AppendLine("    {");
            sb.AppendLine("        public override void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.Initialize();");
            sb.AppendLine("            // Initialize service");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void Shutdown()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Cleanup service");
            sb.AppendLine("            base.Shutdown();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates a Component template (unmanaged struct).
        /// </summary>
        public static string GenerateComponent(string className, string namespaceName)
        {
            if (!className.EndsWith("Component"))
                className += "Component";

            var usings = UsingStatementGenerator.GenerateUsingBlock(
                TemplateContextDetector.TemplateType.Component);

            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine(usings);
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// ECS Component data. Must be an unmanaged struct (no reference types).");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"    public struct {className} : IComponent");
            sb.AppendLine("    {");
            sb.AppendLine("        // Add component fields here (only unmanaged types allowed)");
            sb.AppendLine("        // Examples: int, float, bool, Vector3, etc.");
            sb.AppendLine("        ");
            sb.AppendLine("        public int Value;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates a View template.
        /// </summary>
        public static string GenerateView(string className, string namespaceName)
        {
            if (!className.EndsWith("View"))
                className += "View";

            var usings = UsingStatementGenerator.GenerateUsingBlock(
                TemplateContextDetector.TemplateType.View);

            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine(usings);
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// View component for UI/visual representation.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public class {className} : View");
            sb.AppendLine("    {");
            sb.AppendLine("        public override void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.Initialize();");
            sb.AppendLine("            // Initialize view");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnShow()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Called when view becomes visible");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnHide()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Called when view is hidden");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates a ConfigData template.
        /// </summary>
        public static string GenerateConfig(string className, string namespaceName)
        {
            // Ensure CD_ prefix
            if (!className.StartsWith("CD_"))
                className = "CD_" + className;

            var usings = UsingStatementGenerator.GenerateUsingBlock(
                TemplateContextDetector.TemplateType.Config);

            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine(usings);
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Configuration data asset.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    [CreateAssetMenu(fileName = \"{className}\", menuName = \"Strada/Config/{className.Replace("CD_", "")}\")]");
            sb.AppendLine($"    public class {className} : ScriptableObject");
            sb.AppendLine("    {");
            sb.AppendLine("        [Header(\"Configuration\")]");
            sb.AppendLine("        [SerializeField] private int _value = 0;");
            sb.AppendLine();
            sb.AppendLine("        public int Value => _value;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Validates the configuration data.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <returns>True if valid, false otherwise.</returns>");
            sb.AppendLine("        public virtual bool Validate()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Add validation logic here");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates a Command template for StradaBus.
        /// </summary>
        public static string GenerateCommand(string className, string namespaceName)
        {
            if (!className.EndsWith("Command"))
                className += "Command";

            var usings = UsingStatementGenerator.GenerateUsingBlock(
                TemplateContextDetector.TemplateType.Command);

            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine(usings);
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Command message for StradaBus.");
            sb.AppendLine("    /// Use with bus.Send() to dispatch commands.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public readonly struct {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        // Add command parameters here");
            sb.AppendLine("        public readonly int Value;");
            sb.AppendLine();
            sb.AppendLine($"        public {className}(int value)");
            sb.AppendLine("        {");
            sb.AppendLine("            Value = value;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates an Event template for StradaBus.
        /// </summary>
        public static string GenerateEvent(string className, string namespaceName)
        {
            if (!className.EndsWith("Event"))
                className += "Event";

            var usings = UsingStatementGenerator.GenerateUsingBlock(
                TemplateContextDetector.TemplateType.Event);

            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine(usings);
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Event message for StradaBus.");
            sb.AppendLine("    /// Use with bus.Publish() to broadcast events.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public readonly struct {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        // Add event data here");
            sb.AppendLine("        public readonly int Value;");
            sb.AppendLine();
            sb.AppendLine($"        public {className}(int value)");
            sb.AppendLine("        {");
            sb.AppendLine("            Value = value;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates a template based on the template type.
        /// </summary>
        public static string GenerateTemplate(
            TemplateContextDetector.TemplateType templateType,
            string className,
            string namespaceName)
        {
            return templateType switch
            {
                TemplateContextDetector.TemplateType.System => GenerateSystem(className, namespaceName),
                TemplateContextDetector.TemplateType.Controller => GenerateController(className, namespaceName),
                TemplateContextDetector.TemplateType.Service => GenerateService(className, namespaceName),
                TemplateContextDetector.TemplateType.Component => GenerateComponent(className, namespaceName),
                TemplateContextDetector.TemplateType.View => GenerateView(className, namespaceName),
                TemplateContextDetector.TemplateType.Config => GenerateConfig(className, namespaceName),
                TemplateContextDetector.TemplateType.Command => GenerateCommand(className, namespaceName),
                TemplateContextDetector.TemplateType.Event => GenerateEvent(className, namespaceName),
                _ => GenerateGenericClass(className, namespaceName)
            };
        }

        /// <summary>
        /// Generates a generic class template.
        /// </summary>
        private static string GenerateGenericClass(string className, string namespaceName)
        {
            var sb = new StringBuilder();
            sb.Append(GeneratedHeader);
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {className} class.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Creates a file from a template at the specified path.
        /// </summary>
        public static bool CreateFileFromTemplate(
            TemplateContextDetector.TemplateType templateType,
            string className,
            string folderPath)
        {
            try
            {
                var namespaceName = TemplateContextDetector.ExtractNamespace(folderPath);
                var code = GenerateTemplate(templateType, className, namespaceName);

                // Determine file name with appropriate suffix
                var fileName = GetFileNameForTemplate(templateType, className);
                var filePath = Path.Combine(folderPath, fileName);

                // Ensure directory exists
                Directory.CreateDirectory(folderPath);

                // Write file
                File.WriteAllText(filePath, code);

                // Refresh asset database
                AssetDatabase.Refresh();

                Debug.Log($"[Strada] Created {templateType} template: {filePath}");
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Strada] Failed to create template: {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Gets the appropriate file name for a template type.
        /// </summary>
        private static string GetFileNameForTemplate(
            TemplateContextDetector.TemplateType templateType,
            string className)
        {
            var suffix = templateType switch
            {
                TemplateContextDetector.TemplateType.System => "System",
                TemplateContextDetector.TemplateType.Controller => "Controller",
                TemplateContextDetector.TemplateType.Service => "Service",
                TemplateContextDetector.TemplateType.Component => "Component",
                TemplateContextDetector.TemplateType.View => "View",
                TemplateContextDetector.TemplateType.Config => "",
                TemplateContextDetector.TemplateType.Command => "Command",
                TemplateContextDetector.TemplateType.Event => "Event",
                _ => ""
            };

            // Handle CD_ prefix for configs
            if (templateType == TemplateContextDetector.TemplateType.Config)
            {
                if (!className.StartsWith("CD_"))
                    className = "CD_" + className;
            }
            else if (!string.IsNullOrEmpty(suffix) && !className.EndsWith(suffix))
            {
                className += suffix;
            }

            return className + ".cs";
        }
    }
}
