// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by Strada Module Generator v1.0
// =============================================================================

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Strada.Core.Editor.CodeGen;
using UnityEditor;
using UnityEngine;

namespace Strada.Core.Editor.Windows
{
    /// <summary>
    /// Enhanced module generator window with namespace configuration,
    /// dependency selection, and preview panel.
    /// </summary>
    public class StradaModuleGeneratorWindow : EditorWindow
    {
        private const string GeneratorVersion = "1.0";
        
        // Module configuration
        private string _moduleName = "";
        private string _namespace = "Game.Modules";
        private string _targetPath = "Assets/Modules";
        
        // Component toggles
        private bool _createController = true;
        private bool _createService = true;
        private bool _createSystem = true;
        private bool _createConfig = true;
        private bool _createInterfaces = true;
        private bool _createComponents = true;
        private bool _createTests = false;
        
        // Dependencies
        private List<string> _availableModules = new List<string>();
        private List<string> _selectedDependencies = new List<string>();
        private string _dependencySearchText = "";
        private bool _showDependencyDropdown = false;
        
        // UI state
        private Vector2 _scrollPosition;
        private Vector2 _previewScrollPosition;
        private Vector2 _dependencyScrollPosition;
        
        // Validation
        private ModuleNameValidationResult _validationResult;

        public static void ShowWindow()
        {
            var window = GetWindow<StradaModuleGeneratorWindow>("Create Module");
            window.minSize = new Vector2(550, 650);
            window.Show();
        }

        private void OnEnable()
        {
            RefreshAvailableModules();
        }

        private void OnGUI()
        {
            _scrollPosition = EditorGUILayout.BeginScrollView(_scrollPosition);

            DrawHeader();
            DrawModuleConfiguration();
            DrawDependencySelection();
            DrawComponentSelection();
            DrawGenerateButton();
            DrawPreviewPanel();

            EditorGUILayout.EndScrollView();
        }

        private void DrawHeader()
        {
            EditorGUILayout.Space(10);
            GUILayout.Label("Strada Module Generator", new GUIStyle(EditorStyles.boldLabel) { fontSize = 16 });
            EditorGUILayout.HelpBox(
                "Create a new Strada module with proper structure, namespace, and dependencies.",
                MessageType.Info);
            EditorGUILayout.Space(10);
        }

        private void DrawModuleConfiguration()
        {
            EditorGUILayout.LabelField("Module Configuration", EditorStyles.boldLabel);
            EditorGUI.indentLevel++;

            // Module Name with validation
            EditorGUILayout.LabelField("Module Name:");
            EditorGUI.BeginChangeCheck();
            _moduleName = EditorGUILayout.TextField(_moduleName);
            if (EditorGUI.EndChangeCheck())
            {
                _moduleName = SanitizeModuleName(_moduleName);
                _validationResult = ValidateModuleName(_moduleName);
            }

            // Show validation feedback
            if (!string.IsNullOrEmpty(_moduleName))
            {
                if (_validationResult.IsValid)
                {
                    EditorGUILayout.HelpBox("✓ Valid module name", MessageType.None);
                }
                else
                {
                    EditorGUILayout.HelpBox(_validationResult.ErrorMessage, MessageType.Warning);
                }
            }

            EditorGUILayout.Space(5);

            // Root Namespace
            EditorGUILayout.LabelField("Root Namespace:");
            _namespace = EditorGUILayout.TextField(_namespace);

            EditorGUILayout.Space(5);

            // Target Path
            EditorGUILayout.LabelField("Target Path:");
            EditorGUILayout.BeginHorizontal();
            _targetPath = EditorGUILayout.TextField(_targetPath);
            if (GUILayout.Button("...", GUILayout.Width(30)))
            {
                var path = EditorUtility.OpenFolderPanel("Select Module Location", "Assets", "");
                if (!string.IsNullOrEmpty(path))
                    _targetPath = "Assets" + path.Substring(Application.dataPath.Length);
            }
            EditorGUILayout.EndHorizontal();

            EditorGUI.indentLevel--;
            EditorGUILayout.Space(10);
        }

        private void DrawDependencySelection()
        {
            EditorGUILayout.LabelField("Module Dependencies", EditorStyles.boldLabel);
            EditorGUI.indentLevel++;

            // Search field with autocomplete
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField("Add Dependency:", GUILayout.Width(100));
            
            EditorGUI.BeginChangeCheck();
            _dependencySearchText = EditorGUILayout.TextField(_dependencySearchText);
            if (EditorGUI.EndChangeCheck())
            {
                _showDependencyDropdown = !string.IsNullOrEmpty(_dependencySearchText);
            }

            if (GUILayout.Button("Refresh", GUILayout.Width(60)))
            {
                RefreshAvailableModules();
            }
            EditorGUILayout.EndHorizontal();

            // Autocomplete dropdown
            if (_showDependencyDropdown && !string.IsNullOrEmpty(_dependencySearchText))
            {
                var filteredModules = _availableModules
                    .Where(m => m.IndexOf(_dependencySearchText, StringComparison.OrdinalIgnoreCase) >= 0)
                    .Where(m => !_selectedDependencies.Contains(m))
                    .Take(5)
                    .ToList();

                if (filteredModules.Count > 0)
                {
                    EditorGUILayout.BeginVertical(EditorStyles.helpBox);
                    _dependencyScrollPosition = EditorGUILayout.BeginScrollView(
                        _dependencyScrollPosition, GUILayout.MaxHeight(100));
                    
                    foreach (var module in filteredModules)
                    {
                        if (GUILayout.Button(module, EditorStyles.label))
                        {
                            _selectedDependencies.Add(module);
                            _dependencySearchText = "";
                            _showDependencyDropdown = false;
                            GUI.FocusControl(null);
                        }
                    }
                    
                    EditorGUILayout.EndScrollView();
                    EditorGUILayout.EndVertical();
                }
            }

            // Selected dependencies
            if (_selectedDependencies.Count > 0)
            {
                EditorGUILayout.Space(5);
                EditorGUILayout.LabelField("Selected Dependencies:");
                
                for (int i = _selectedDependencies.Count - 1; i >= 0; i--)
                {
                    EditorGUILayout.BeginHorizontal();
                    EditorGUILayout.LabelField($"  • {_selectedDependencies[i]}");
                    if (GUILayout.Button("×", GUILayout.Width(20)))
                    {
                        _selectedDependencies.RemoveAt(i);
                    }
                    EditorGUILayout.EndHorizontal();
                }
            }
            else
            {
                EditorGUILayout.HelpBox("No dependencies selected. Type to search for existing modules.", MessageType.None);
            }

            EditorGUI.indentLevel--;
            EditorGUILayout.Space(10);
        }

        private void DrawComponentSelection()
        {
            EditorGUILayout.LabelField("Components to Generate", EditorStyles.boldLabel);
            EditorGUI.indentLevel++;

            _createInterfaces = EditorGUILayout.Toggle("Service Interface", _createInterfaces);
            _createController = EditorGUILayout.Toggle("Controller", _createController);
            _createService = EditorGUILayout.Toggle("Service", _createService);
            _createSystem = EditorGUILayout.Toggle("ECS System", _createSystem);
            _createComponents = EditorGUILayout.Toggle("ECS Component", _createComponents);
            _createConfig = EditorGUILayout.Toggle("Config Data (CD_*)", _createConfig);
            _createTests = EditorGUILayout.Toggle("Unit Tests", _createTests);

            EditorGUI.indentLevel--;
            EditorGUILayout.Space(10);
        }

        private void DrawGenerateButton()
        {
            bool isValid = _validationResult?.IsValid ?? false;
            
            EditorGUI.BeginDisabledGroup(!isValid || string.IsNullOrEmpty(_moduleName));
            if (GUILayout.Button("Generate Module", GUILayout.Height(40)))
            {
                GenerateModule();
            }
            EditorGUI.EndDisabledGroup();

            if (string.IsNullOrEmpty(_moduleName))
            {
                EditorGUILayout.HelpBox("Enter a module name to continue.", MessageType.Info);
            }
        }

        private void DrawPreviewPanel()
        {
            if (string.IsNullOrEmpty(_moduleName) || !(_validationResult?.IsValid ?? false))
                return;

            EditorGUILayout.Space(10);
            EditorGUILayout.LabelField("Preview", EditorStyles.boldLabel);
            
            _previewScrollPosition = EditorGUILayout.BeginScrollView(
                _previewScrollPosition, 
                EditorStyles.helpBox, 
                GUILayout.MinHeight(200));
            
            var preview = GeneratePreview();
            EditorGUILayout.LabelField(preview, new GUIStyle(EditorStyles.label) { wordWrap = true });
            
            EditorGUILayout.EndScrollView();
        }

        #region Validation

        private static string SanitizeModuleName(string name)
        {
            return ModuleNameValidator.Sanitize(name);
        }

        /// <summary>
        /// Validates a module name according to PascalCase convention and reserved names.
        /// Delegates to ModuleNameValidator for actual validation logic.
        /// </summary>
        public static ModuleNameValidationResult ValidateModuleName(string name)
        {
            return ModuleNameValidator.Validate(name);
        }

        #endregion

        #region Module Discovery

        private void RefreshAvailableModules()
        {
            _availableModules.Clear();
            
            // Find all IModuleInstaller implementations
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            var installerType = typeof(Modules.IModuleInstaller);
            
            foreach (var assembly in assemblies)
            {
                try
                {
                    var types = assembly.GetTypes()
                        .Where(t => installerType.IsAssignableFrom(t) && 
                                   t.IsClass && 
                                   !t.IsAbstract);
                    
                    foreach (var type in types)
                    {
                        _availableModules.Add(type.Name);
                    }
                }
                catch
                {
                    // Skip assemblies that can't be scanned
                }
            }
            
            _availableModules.Sort();
        }

        #endregion

        #region Preview Generation

        private string GeneratePreview()
        {
            var sb = new StringBuilder();
            var ns = GetFullNamespace();
            
            sb.AppendLine($"📁 {_targetPath}/{_moduleName}Module/");
            sb.AppendLine($"   Namespace: {ns}");
            sb.AppendLine();
            
            sb.AppendLine("   📁 Scripts/");
            
            if (_createInterfaces)
                sb.AppendLine($"      📁 Interfaces/");
            if (_createInterfaces)
                sb.AppendLine($"         📄 I{_moduleName}Service.cs");
            
            if (_createController)
            {
                sb.AppendLine($"      📁 Controllers/");
                sb.AppendLine($"         📄 {_moduleName}Controller.cs");
            }
            
            if (_createService)
            {
                sb.AppendLine($"      📁 Services/");
                sb.AppendLine($"         📄 {_moduleName}Service.cs");
            }
            
            if (_createSystem)
            {
                sb.AppendLine($"      📁 Systems/");
                sb.AppendLine($"         📄 {_moduleName}System.cs");
            }
            
            if (_createComponents)
            {
                sb.AppendLine($"      📁 Components/");
                sb.AppendLine($"         📄 {_moduleName}Component.cs");
            }
            
            if (_createConfig)
            {
                sb.AppendLine($"      📁 Data/");
                sb.AppendLine($"         📁 UnityObjects/");
                sb.AppendLine($"            📄 CD_{_moduleName}.cs");
                sb.AppendLine($"         📁 ValueObjects/");
                sb.AppendLine($"            📄 {_moduleName}Config.cs");
            }
            
            sb.AppendLine();
            sb.AppendLine($"   📄 {_moduleName}Module.cs");
            sb.AppendLine($"   📄 {_moduleName}.asmdef");
            
            if (_createTests)
            {
                sb.AppendLine();
                sb.AppendLine($"   📁 Tests/");
                sb.AppendLine($"      📄 {_moduleName}Tests.cs");
                sb.AppendLine($"      📄 {_moduleName}.Tests.asmdef");
            }
            
            if (_selectedDependencies.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("   Dependencies:");
                foreach (var dep in _selectedDependencies)
                {
                    sb.AppendLine($"      → {dep}");
                }
            }
            
            return sb.ToString();
        }

        private string GetFullNamespace() => $"{_namespace}.{_moduleName}";

        #endregion

        #region Code Generation

        private void GenerateModule()
        {
            var basePath = $"{_targetPath}/{_moduleName}Module";
            var ns = GetFullNamespace();

            CreateDirectory(basePath);
            CreateDirectory($"{basePath}/Scripts");
            
            if (_createInterfaces) CreateDirectory($"{basePath}/Scripts/Interfaces");
            if (_createController) CreateDirectory($"{basePath}/Scripts/Controllers");
            if (_createService) CreateDirectory($"{basePath}/Scripts/Services");
            if (_createSystem) CreateDirectory($"{basePath}/Scripts/Systems");
            if (_createComponents) CreateDirectory($"{basePath}/Scripts/Components");
            if (_createConfig)
            {
                CreateDirectory($"{basePath}/Scripts/Data/UnityObjects");
                CreateDirectory($"{basePath}/Scripts/Data/ValueObjects");
            }

            CreateModuleClass(basePath, ns);
            CreateAssemblyDefinition(basePath, ns);

            if (_createInterfaces) CreateInterface(basePath, ns);
            if (_createController) CreateController(basePath, ns);
            if (_createService) CreateService(basePath, ns);
            if (_createSystem) CreateSystem(basePath, ns);
            if (_createComponents) CreateComponent(basePath, ns);
            if (_createConfig) CreateConfig(basePath, ns);
            if (_createTests) CreateTests(basePath, ns);

            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog("Module Created", 
                $"{_moduleName} module created at:\n{basePath}", "OK");
        }

        private void CreateDirectory(string path)
        {
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);
        }

        private string GenerateFileHeader()
        {
            return $@"// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by Strada Module Generator v{GeneratorVersion}
// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================

";
        }

        private void CreateModuleClass(string basePath, string ns)
        {
            var dependsOnAttribute = "";
            var dependsOnUsing = "";
            
            if (_selectedDependencies.Count > 0)
            {
                var depTypes = string.Join(", ", _selectedDependencies.Select(d => $"typeof({d})"));
                dependsOnAttribute = $"\n    [ModuleDependsOn({depTypes})]";
                dependsOnUsing = "\nusing Strada.Core.Modules;";
            }

            var content = GenerateFileHeader() + $@"using Strada.Core.DI;
using Strada.Core.Modules;{dependsOnUsing}

namespace {ns}
{{{dependsOnAttribute}
    public sealed class {_moduleName}Module : IModuleInstaller
    {{
        public string Name => ""{_moduleName}"";

        public void Install(IContainerBuilder builder)
        {{{(_createService && _createInterfaces ? $@"
            builder.Register<I{_moduleName}Service, {_moduleName}Service>(Lifetime.Singleton);" : "")}{(_createController ? $@"
            builder.Register<{_moduleName}Controller>(Lifetime.Singleton);" : "")}
        }}

        public void Initialize(IContainer container)
        {{
        }}

        public void Shutdown()
        {{
        }}
    }}
}}
";
            File.WriteAllText($"{basePath}/{_moduleName}Module.cs", content);
        }

        private void CreateAssemblyDefinition(string basePath, string ns)
        {
            var references = new List<string> { "Strada.Core" };
            
            // Add dependency assembly references
            foreach (var dep in _selectedDependencies)
            {
                // Try to find the assembly name for the dependency
                var depAssembly = FindAssemblyForModule(dep);
                if (!string.IsNullOrEmpty(depAssembly) && !references.Contains(depAssembly))
                {
                    references.Add(depAssembly);
                }
            }

            var referencesJson = string.Join(",\n        ", references.Select(r => $"\"{r}\""));
            
            var content = $@"{{
    ""name"": ""{ns}"",
    ""rootNamespace"": ""{ns}"",
    ""references"": [
        {referencesJson}
    ],
    ""includePlatforms"": [],
    ""excludePlatforms"": [],
    ""allowUnsafeCode"": true,
    ""overrideReferences"": false,
    ""precompiledReferences"": [],
    ""autoReferenced"": true,
    ""defineConstraints"": [],
    ""versionDefines"": [],
    ""noEngineReferences"": false
}}";
            File.WriteAllText($"{basePath}/{_moduleName}.asmdef", content);
        }

        private string FindAssemblyForModule(string moduleName)
        {
            // Try to find the assembly containing this module
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            var installerType = typeof(Modules.IModuleInstaller);
            
            foreach (var assembly in assemblies)
            {
                try
                {
                    var type = assembly.GetTypes()
                        .FirstOrDefault(t => t.Name == moduleName && 
                                            installerType.IsAssignableFrom(t));
                    
                    if (type != null)
                    {
                        return assembly.GetName().Name;
                    }
                }
                catch
                {
                    // Skip
                }
            }
            
            return null;
        }

        private void CreateInterface(string basePath, string ns)
        {
            var content = GenerateFileHeader() + $@"namespace {ns}
{{
    public interface I{_moduleName}Service
    {{
        void Initialize();
    }}
}}
";
            File.WriteAllText($"{basePath}/Scripts/Interfaces/I{_moduleName}Service.cs", content);
        }

        private void CreateController(string basePath, string ns)
        {
            var content = GenerateFileHeader() + $@"using Strada.Core.MVCS;
using Strada.Core.MVCS.Interfaces;

namespace {ns}
{{
    public sealed class {_moduleName}Controller : IController
    {{{(_createService && _createInterfaces ? $@"
        private readonly I{_moduleName}Service _service;

        public {_moduleName}Controller(I{_moduleName}Service service)
        {{
            _service = service;
        }}" : "")}

        public void Initialize()
        {{
        }}

        public void Update(float deltaTime)
        {{
        }}
    }}
}}
";
            File.WriteAllText($"{basePath}/Scripts/Controllers/{_moduleName}Controller.cs", content);
        }

        private void CreateService(string basePath, string ns)
        {
            var content = GenerateFileHeader() + $@"using Strada.Core.MVCS.Interfaces;

namespace {ns}
{{
    public sealed class {_moduleName}Service : IService{(_createInterfaces ? $", I{_moduleName}Service" : "")}
    {{
        public void Initialize()
        {{
        }}

        public void Update(float deltaTime)
        {{
        }}
    }}
}}
";
            File.WriteAllText($"{basePath}/Scripts/Services/{_moduleName}Service.cs", content);
        }

        private void CreateSystem(string basePath, string ns)
        {
            var content = GenerateFileHeader() + $@"using Strada.Core.ECS;

namespace {ns}
{{
    public sealed class {_moduleName}System : ISystem
    {{
        public void Initialize()
        {{
        }}

        public void Update(float deltaTime)
        {{
        }}

        public void Dispose()
        {{
        }}
    }}
}}
";
            File.WriteAllText($"{basePath}/Scripts/Systems/{_moduleName}System.cs", content);
        }

        private void CreateComponent(string basePath, string ns)
        {
            var content = GenerateFileHeader() + $@"using Strada.Core.ECS;

namespace {ns}
{{
    public struct {_moduleName}Component : IComponent
    {{
    }}
}}
";
            File.WriteAllText($"{basePath}/Scripts/Components/{_moduleName}Component.cs", content);
        }

        private void CreateConfig(string basePath, string ns)
        {
            var configContent = GenerateFileHeader() + $@"using System;

namespace {ns}
{{
    [Serializable]
    public sealed class {_moduleName}Config
    {{
    }}
}}
";
            File.WriteAllText($"{basePath}/Scripts/Data/ValueObjects/{_moduleName}Config.cs", configContent);

            var cdContent = GenerateFileHeader() + $@"using Strada.Core.Data;
using UnityEngine;

namespace {ns}
{{
    [CreateAssetMenu(fileName = ""CD_{_moduleName}"", menuName = ""Strada/Config/{_moduleName}"")]
    public sealed class CD_{_moduleName} : ConfigData<{_moduleName}Config>
    {{
    }}
}}
";
            File.WriteAllText($"{basePath}/Scripts/Data/UnityObjects/CD_{_moduleName}.cs", cdContent);
        }

        private void CreateTests(string basePath, string ns)
        {
            CreateDirectory($"{basePath}/Tests");

            var testContent = GenerateFileHeader() + $@"using NUnit.Framework;

namespace {ns}.Tests
{{
    [TestFixture]
    public class {_moduleName}Tests
    {{
        [SetUp]
        public void SetUp()
        {{
        }}

        [TearDown]
        public void TearDown()
        {{
        }}

        [Test]
        public void Example_Test()
        {{
            Assert.Pass();
        }}
    }}
}}
";
            File.WriteAllText($"{basePath}/Tests/{_moduleName}Tests.cs", testContent);

            var testAsmdef = $@"{{
    ""name"": ""{ns}.Tests"",
    ""rootNamespace"": ""{ns}.Tests"",
    ""references"": [
        ""{ns}"",
        ""Strada.Core"",
        ""UnityEngine.TestRunner"",
        ""UnityEditor.TestRunner""
    ],
    ""includePlatforms"": [
        ""Editor""
    ],
    ""excludePlatforms"": [],
    ""allowUnsafeCode"": true,
    ""overrideReferences"": true,
    ""precompiledReferences"": [
        ""nunit.framework.dll""
    ],
    ""autoReferenced"": false,
    ""defineConstraints"": [
        ""UNITY_INCLUDE_TESTS""
    ],
    ""versionDefines"": [],
    ""noEngineReferences"": false
}}";
            File.WriteAllText($"{basePath}/Tests/{_moduleName}.Tests.asmdef", testAsmdef);
        }

        #endregion
    }

}
