using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Strada.SourceGeneration
{
    [Generator]
    public sealed class StradaFactoryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidateClass(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndClasses,
                static (spc, source) => Execute(source.Left, source.Right!, spc));
        }

        private static bool IsCandidateClass(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDecl &&
                   classDecl.AttributeLists.Count > 0;
        }

        private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDecl = (ClassDeclarationSyntax)context.Node;

            foreach (var attributeList in classDecl.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    var symbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol;
                    if (symbol is not IMethodSymbol methodSymbol)
                        continue;

                    var containingType = methodSymbol.ContainingType;
                    if (containingType.ToDisplayString() == "Strada.Core.DI.Attributes.StradaServiceAttribute")
                        return classDecl;
                }
            }

            return null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax?> classes, SourceProductionContext context)
        {
            if (classes.IsDefaultOrEmpty)
                return;

            var distinctClasses = classes.Where(c => c is not null).Distinct().ToList();
            if (distinctClasses.Count == 0)
                return;

            var serviceInfos = new List<ServiceInfo>();

            foreach (var classDecl in distinctClasses)
            {
                var model = compilation.GetSemanticModel(classDecl!.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(classDecl);
                if (symbol is not INamedTypeSymbol namedSymbol)
                    continue;

                var info = ExtractServiceInfo(namedSymbol);
                if (info != null)
                    serviceInfos.Add(info);
            }

            if (serviceInfos.Count == 0)
                return;

            var source = GenerateSource(serviceInfos);
            context.AddSource("Strada.Generated.Factories.g.cs", SourceText.From(source, Encoding.UTF8));
        }

        private static ServiceInfo? ExtractServiceInfo(INamedTypeSymbol symbol)
        {
            if (symbol.IsAbstract || symbol.IsStatic)
                return null;

            var constructor = symbol.Constructors
                .Where(c => c.DeclaredAccessibility == Accessibility.Public && !c.IsStatic)
                .OrderByDescending(c => c.Parameters.Length)
                .FirstOrDefault();

            if (constructor == null)
                return null;

            var dependencies = constructor.Parameters
                .Select(p => new DependencyInfo
                {
                    TypeName = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    ParameterName = p.Name
                })
                .ToList();

            return new ServiceInfo
            {
                TypeName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                ClassName = symbol.Name,
                Namespace = symbol.ContainingNamespace.ToDisplayString(),
                Dependencies = dependencies
            };
        }

        private static string GenerateSource(List<ServiceInfo> services)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Strada.Core.DI;");
            sb.AppendLine();
            sb.AppendLine("namespace Strada.Generated");
            sb.AppendLine("{");

            foreach (var service in services)
            {
                GenerateFactory(sb, service);
            }

            GenerateInitializer(sb, services);

            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void GenerateFactory(StringBuilder sb, ServiceInfo service)
        {
            var factoryName = $"{service.ClassName}_Factory";
            var deps = service.Dependencies;

            sb.AppendLine($"    internal static class {factoryName}");
            sb.AppendLine("    {");
            sb.Append($"        internal static {service.TypeName} Create(IContainer c) => new {service.TypeName}(");

            for (int i = 0; i < deps.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append($"c.Resolve<{deps[i].TypeName}>()");
            }

            sb.AppendLine(");");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void GenerateInitializer(StringBuilder sb, List<ServiceInfo> services)
        {
            sb.AppendLine("    internal static class StradaGeneratedInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("        internal static void Initialize()");
            sb.AppendLine("        {");

            foreach (var service in services)
            {
                var factoryName = $"{service.ClassName}_Factory";
                sb.AppendLine($"            DirectFactory<{service.TypeName}>.Delegate = {factoryName}.Create;");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private sealed class ServiceInfo
        {
            public string TypeName { get; set; } = "";
            public string ClassName { get; set; } = "";
            public string Namespace { get; set; } = "";
            public List<DependencyInfo> Dependencies { get; set; } = new();
        }

        private sealed class DependencyInfo
        {
            public string TypeName { get; set; } = "";
            public string ParameterName { get; set; } = "";
        }
    }
}
